### ISSUE TITLE
bug: Kurs download schlägt für inaktive Wertpapiere fehl

### ISSUE THREAD

**Issue by Marfir** [portfolio-performance/portfolio#1112]
Inaktive Wertpapiere wurden bisher vom Kursdownload ignoriert. Das ist auch korrekt so. Seit der Version 0.38.0 scheint das aber nicht mehr der Fall zu sein.

Das Fehlerlog ist nun voll mit Meldungen, z. B.:
`java.io.IOException: Downloadfehler bei Versuch 1 für Ticker L3D.F: https://query1.finance.yahoo.com/v7/finance/spark?symbols=L3D.F&range=5y&interval=1d --> 404
	at name.abuchen.portfolio.online.impl.YahooFinanceQuoteFeed.internalGetQuotes(YahooFinanceQuoteFeed.java:214)
	at name.abuchen.portfolio.online.impl.YahooFinanceQuoteFeed.updateHistoricalQuotes(YahooFinanceQuoteFeed.java:154)`

Ich habe Wertpapiere wie z. B. Lake Shore Gold deaktiviert, weil diese nicht mehr als eigenständige Firma existieren. Der Kursdownload sollte inaktive Wertpapiere wieder ignorieren.

**Comment by Ragas13** [comment]
Ehrlich gesagt bin ich mir nicht sicher ob es jemals so wie du beschreibst funktioniert hat.

However du kannst im Wertpapier den Download der Kurse deaktivieren.

**Comment by Marfir** [comment]
Ach ich weis wieso. Unter "aktueller Kurs" ist der automatische download deaktiviert. Da seit dieser Version die Update-Funktion für historische und aktuellen Kurs zusammen gelegt wurde, ist das jetzt inkonsistent.
Die beiden Reiter müssten jetzt auch zusammen gelegt werden, um dass es wieder stimmig ist.

Ehrlich gesagt ist das auch umständlich, dass man 3 Schalter umlegen muss nur um ein Wertpapier deaktivieren zu können.

**Comment by buchen** [comment]
> Inaktive Wertpapiere wurden bisher vom Kursdownload ignoriert.

Inaktive Wertpapiere wurden bisher *nicht* vom Kursdownload ausgenommen. Die Kurse werden nicht geladen, wenn das Wertpapier als "Kein Automatischer Download" konfiguriert ist.

Inaktive Wertpapiere werden in den Dialogen ausgeblendet (wenn man zum Beispiel einen neue Kauforder anlegt). Man kann das auch für Wertpapiere nutzen, die rein als Benchmark gelten - man also Kurse laden möchte, aber nicht ständig die Option haben möchte das Wertpapier zu kaufen.

Die Frage kommt aber immer wieder. Ich habe ja schon einen Infotext zu dem Attribut hinzugefügt, aber trotzdem scheint das zu irritieren.
 
<img width="736" alt="bildschirmfoto 2019-02-12 um 09 14 11" src="https://user-images.githubusercontent.com/587976/52621039-96be1800-2ea6-11e9-8716-2e1cbc9a2aa1.png">

Ich könnte noch ein weitere Checkbox machen "kein Kursdownload". Aber: selbst wenn man da den Kursdownload aktiviert, muss der ja nicht konfiguriert sein. Es reicht leider nicht nur zu sagen, dass man Kurse laden möchte. PP muss wissen wo die her kommen sollen. Darum habe ich das bisher nicht gemacht.

Ich könnte aber auf der ersten Seite auch anzeigen ob ein Kursdownload konfiguriert ist. Und dann wechselt man auf den entsprechenden Reiter um das zu konfigurieren. Was meint Ihr?

**Comment by Marfir** [comment]
Ja sorry. Meine Verwirrung entstand weil ich den Kursdownload für den aktuellen Tag deaktiviert hatte und in der Vergangenheit immer auf "manuellen Kursdownload von heute" geklickt habe. Da wurden die ignoriert.
Jetzt wo im Menü der Kursdownload eine Funktion ist (heute+historisch) aber der Reiter "aktueller Kurs" im Wertpapier ignoriert wird, verwirrt es halt weiterhin.

Sauber wäre die beiden Reiter zusammen zu legen.

Und im Hauptreiter könnte man zwei Häckchen anbieten:
- inaktiv aber mit Kursdownload
- inaktiv inkl. deaktiviertem Kursdownload

Bzw. brauchen User wirklich den Kursdownload wenn das Wertpapier deaktiviert ist? Ansonsten könnte man das auch vereinfachen.

**Comment by buchen** [comment]
> Jetzt wo im Menü der Kursdownload eine Funktion ist (heute+historisch) aber die Einstellung im Reiter "aktueller Kurs" im Wertpapier ignoriert wird, verwirrt es halt weiterhin.

Verstehe ich das richtig: Du hast den Kurs-Download für den aktuellen Kurs deaktiviert (nicht aber für die historischen Kurse) und wenn Du im Menü "Online" -> "Kurse aktualisieren" wählst, dann werden der aktuelle Kurs trotzdem aktualisiert?!? Mach mal einen Screenshot von beiden Reitern.

> Sauber wäre die beiden Reiter zusammen zu legen.

Das sind halt technisch zwei verschiedene Sachen und müssen unterschiedlich konfiguriert werden.

> Bzw. brauchen User wirklich den Kursdownload wenn das Wertpapier deaktiviert ist?

Weil "deaktiviert" eben bedeutet, dass das Wertpapier nicht zum Kauf/Verkauf in den Dropdowns auftaucht. Man es also aus den Dialogen ausblenden möchte. Trotzdem möchte man die Kurse laden.

Umgekehrt geht es ja auch: man möchte keine Kurse automatisch laden (weil es das nicht gibt) sonder muss sie zwangsläufig manuell erfassen, aber trotzdem ist das Wertpapier "aktiv" und kann gekauft/verkauft werden.

**Comment by Marfir** [comment]
Ja das hast du richtig verstanden. Inzwischen habe ich auch im historischen Reiter den Kursdownload deaktiviert. Seit dem kommen keine Download-Fehler mehr.
Das müsstest du in einem Unit Test leicht nachstellen können.

Wie schon bei einem anderen issue besprochen, bin ich der Meinung das Kurse nicht unterschiedlich behandelt werden sollten. Der Kurs von heute wird morgen der historische sein. ;-)

Stimmt, dass hatte ich nicht bedacht. So könnte man auch Firmen in PP führen, die (nicht mehr) an der Börse gehandelt werden. Ich hatte bisher meine Papiere deaktiviert, weil diese Firmen übernommen wurden und somit keine künftigen Kurse verfügbar sein werden.
----
Alternativ könnte PP auch den Kursdownload selbst deaktivieren, wenn Yahoo meldet, dass das Wertpapier/Börsenkürzel unbekannt ist. Aber das ist vielleicht zu viel automatik.
