### ISSUE TITLE
Support macOS Big Sur (10.16)

### ISSUE THREAD

**Issue by buchen** [portfolio-performance/portfolio#1621]
Errors reported in PP forum:
https://forum.portfolio-performance.info/t/java-lang-nullpointerexception-on-mac-os-big-sur/9884/9

```
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.internal_new_GC(Control.java:2180)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:177)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:138)
	at org.eclipse.swt.custom.CTabFolder.updateTabHeight(CTabFolder.java:3810)
```

But: we have not updated SWT for quite some time (March 2019). Before opening a bug, we should test with the latest SWT.

**Comment by fazzer4x** [comment]
Big Sur Public Beta
PP was running fine on Catalina a few hours ago. 

Now PP throws following error at me: 

`Thu Aug 13 01:03:26 CEST 2020


java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.internal_new_GC(Control.java:2180)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:177)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:138)
	at org.eclipse.swt.custom.CTabFolder.updateTabHeight(CTabFolder.java:3810)
	at org.eclipse.swt.custom.CTabFolder.runUpdate(CTabFolder.java:3843)
	at org.eclipse.swt.custom.CTabItem.getBounds(CTabItem.java:156)
	at org.eclipse.swt.custom.CTabFolder.onPaint(CTabFolder.java:2080)
	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:337)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4292)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Control.drawWidget(Control.java:1279)
	at org.eclipse.swt.widgets.Widget.drawRect(Widget.java:776)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5929)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:5183)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5607)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(NSApplication.java:97)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3727)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:165)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)

`

**Comment by buchen** [comment]
Refresh Light Mac Theme to fit Mac OS 11 Big Sur
https://bugs.eclipse.org/bugs/show_bug.cgi?id=565556

Welcome screen's toolbar has broken background on Mac
https://bugs.eclipse.org/bugs/show_bug.cgi?id=565920

Eclipse fails to launch on MacOs Big Sur
https://bugs.eclipse.org/bugs/show_bug.cgi?id=565913

**Comment by buchen** [comment]
Bugs reported on Eclipse for Big Sur:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=565691

**Comment by adnangul** [comment]
Bug 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=569361

**Comment by ivadoncheva** [comment]
Hi, I updated today my macOs and I got this error. Is there a fix for this at the moment?
