### ISSUE TITLE
java.lang.NullPointerException in Performance calculation

### ISSUE THREAD

**Issue by Gnopps** [portfolio-performance/portfolio#1836]
**Describe the bug**
When going to Performance => Calculation or Performance => Securities only error message is displayed:

```
java.lang.NullPointerException
	at name.abuchen.portfolio.snapshot.security.SecurityPerformanceSnapshot.lambda$1(SecurityPerformanceSnapshot.java:143)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at name.abuchen.portfolio.snapshot.security.SecurityPerformanceSnapshot.extractSecurityRelatedPortfolioTransactions(SecurityPerformanceSnapshot.java:143)
	at name.abuchen.portfolio.snapshot.security.SecurityPerformanceSnapshot.create(SecurityPerformanceSnapshot.java:55)
	at name.abuchen.portfolio.snapshot.ClientPerformanceSnapshot.addCapitalGains(ClientPerformanceSnapshot.java:298)
	at name.abuchen.portfolio.snapshot.ClientPerformanceSnapshot.calculate(ClientPerformanceSnapshot.java:285)
	at name.abuchen.portfolio.snapshot.ClientPerformanceSnapshot.<init>(ClientPerformanceSnapshot.java:181)
	at name.abuchen.portfolio.ui.views.PerformanceView.reportingPeriodUpdated(PerformanceView.java:127)
	at name.abuchen.portfolio.ui.views.PerformanceView.createBody(PerformanceView.java:172)
	at name.abuchen.portfolio.ui.editor.AbstractFinanceView.createViewControl(AbstractFinanceView.java:127)
	at name.abuchen.portfolio.ui.editor.PortfolioPart.createView(PortfolioPart.java:525)
	at name.abuchen.portfolio.ui.editor.PortfolioPart.activateView(PortfolioPart.java:495)
	at name.abuchen.portfolio.ui.editor.PortfolioPart.activateView(PortfolioPart.java:483)
	at name.abuchen.portfolio.ui.editor.ClientEditorSidebar$1.select(ClientEditorSidebar.java:70)
	at name.abuchen.portfolio.ui.editor.ClientEditorSidebar$1.select(ClientEditorSidebar.java:1)
	at name.abuchen.portfolio.ui.editor.Sidebar$Entry.handleMouseDown(Sidebar.java:419)
	at org.eclipse.swt.events.MouseListener$2.mouseDown(MouseListener.java:96)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4213)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4030)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3630)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:166)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)

```

**To Reproduce**
Not sure what I did to start this. Things I've done since I last knew it worked:
* Add USD deposit and securities accounts (normal home currency is EUR)
* Add new taxonomy: Travel => Cruise
* Added two new USD securities from Yahoo search
* Added two transactions to the securities above

**Screenshots**
Error log is attached
[pp-error-2020-11-23.log](https://github.com/buchen/portfolio/files/5583825/pp-error-2020-11-23.log)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.49.2

**Comment by Gnopps** [comment]
I found the transaction that is causing the issue, but I don't understand why. I can add this security fine:
![image](https://user-images.githubusercontent.com/16313148/100124720-af819d00-2e84-11eb-88a7-7be63fd657d0.png)

However, when I add a buy transaction with it, then the bug appears:
![image](https://user-images.githubusercontent.com/16313148/100124784-c32d0380-2e84-11eb-9aea-7fadbfe54912.png)

**Comment by buchen** [comment]
Hi @Gnopps,

thanks for the error report. It is not really clear to me what goes wrong. The error message occurs when PP tries to map transactions to securities, but the security is not known. This should not happen. It could indicate that the internal model is somehow corrupt.

I have now added some code to help better troubleshoot the problem (and avoid the NPE). However, it would greatly help me if you could send me your file to check. Delete other accounts and securities, but leave this security as is. Send it to *portfolio dot performance dot help at gmail dot com*.

**Comment by Gnopps** [comment]
****

> 
> 
> Hi @Gnopps,
> 
> thanks for the error report. It is not really clear to me what goes wrong. The error message occurs when PP tries to map transactions to securities, but the security is not known. This should not happen. It could indicate that the internal model is somehow corrupt.
> 
> I have now added some code to help better troubleshoot the problem (and avoid the NPE). However, it would greatly help me if you could send me your file to check. Delete other accounts and securities, but leave this security as is. Send it to _portfolio dot performance dot help at gmail dot com_.

Thanks for your reply. Email sent now.
