### ISSUE TITLE
PP freezes, when changing allocation percentages in taxonomy

### ISSUE THREAD

**Issue by mknudsen** [portfolio-performance/portfolio#3520]
**Describe the bug**

**To Reproduce**

1. Go to a Taxonomy
2. Click on an Allocation percentage
3. Fiddle with the percentage a bit
4. PP freezes, uses 100% CPU

**Expected behavior**

PP does not freeze but keeps on working

**Screenshots**

See also my screenrecording:

https://github.com/portfolio-performance/portfolio/assets/564654/b64148f3-665d-4d7a-9368-da1e80371612

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura on M1 V 13.5.1 (22G90)
 - Version Portfolio Performance
   - Version: 0.65.1 (Aug 2023)
   - Platform: macosx, aarch64
   - Java: 17.0.5+8-LTS, Azul Systems, Inc.

**Comment by Nirus2000** [comment]
Hello @mknudsen 
Can you please create a DUMP file?

How this works you can find here in this post. (Translate with deepl.com)
https://forum.portfolio-performance.info/t/import-hangt-sich-auf-seit-update/23106/40

Regards
Alex

**Comment by mknudsen** [comment]
Here is the dump file 
[freeze.txt](https://github.com/portfolio-performance/portfolio/files/12446569/freeze.txt)

**Comment by buchen** [comment]
I update the title - I do not think it is specific to changing the allocation percentages, but the framework has issues when switching back and forth from edit mode. I have experienced this before occasionally, but never dared to dive into the SWT source code.

**Comment by buchen** [comment]
Note to myself:
first test if the issue is reproducible with the latest SWT integration build.
if yes, then we would need a reproducible example for the SWT team

**Comment by buchen** [comment]
eclipse-platform/eclipse.platform.ui#1069

**Comment by ReessKennedy** [comment]
+1 and this also looks like related discussion: https://forum.portfolio-performance.info/t/application-hangs-when-editing-transaction-in-line/22840 ... wondering if this is just on Ventura and if I could solve by moving to Sonoma? I am only seeeing Ventura users mention this.

**Comment by AlexanderLill** [comment]
I have created a video to reproduce, see here: https://github.com/portfolio-performance/portfolio/issues/3818#issuecomment-2568424986

**Comment by georgemac-labs** [comment]
I am also experiencing this. It's a fun one, because it's a classic Heisenbug – timing based, easy to reproduce in normal build, but it disappears if I Debug or even just Run from Eclipse!

However you can see CPU is pegged at 100% and thread dump shows:

  at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
  at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:239)
  at org.eclipse.swt.widgets.Widget.mouseDownSuper(Widget.java:1216)
  at org.eclipse.swt.widgets.Widget.mouseDown(Widget.java:1208)
  at org.eclipse.swt.widgets.Control.mouseDown(Control.java:2598)
  at org.eclipse.swt.widgets.Display.windowProc(Display.java:6286)
  at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
  at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:239)
  at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2407)
  ...

Opus has the following theory:

>   The key is callSuper() → objc_msgSendSuper(). This says "Cocoa, do your default handling."
>   Cocoa's default handling of a mouse event on a tree item involves focus management. And on macOS,
>    focus changes can synchronously dispatch new events before returning.
> 
>   So neither side is recursing directly - but each side keeps creating new work for the other
>   before returning. The call stack grows: Java waiting on native waiting on Java waiting on
>   native...

```
  Java                              Native (Cocoa)
  ─────                             ──────────────
  Display.windowProc receives
  mouse event
      │
      └──► Widget.mouseDown()
                │
                └──► callSuper() ──────► objc_msgSendSuper()
                                          "do your default
                                           mouse handling"
                                                │
                     ◄──────────────────────────┘
                     Cocoa's default handling
                     triggers a focus change,
                     which Cocoa dispatches as
                     a NEW event back to Java
                          │
  Display.windowProc ◄────┘
  receives focus event
      │
      └──► handles focus...
                │
                └──► callSuper() ──────► objc_msgSendSuper()
                                                │
                     ◄──────────────────────────┘
                     dispatches another event...

```

No idea if that's correct, but it seems plausible.

Tried a couple of fixes, but no joy:

>   1. Timing guard in ColumnViewerEditorActivationStrategy.isEditorActivationEvent()
> 
>   Added a 200ms debounce that rejected rapid editor activation requests.
> 
>   Why it failed: This check happens at the JFace level, after the native event processing has
>   already begun. The hang occurs in the native Cocoa→SWT ping-pong during Widget.mouseDown() →
>   callSuper() → objc_msgSendSuper(), which is before JFace's editor activation logic is consulted.
> 
>   2. Mouse listener on Tree widget with event.doit = false
> 
>   Added a SWT.MouseDown listener that detected clicks within 100ms and set event.doit = false /
>   event.type = SWT.None to drop them.
> 
>   Why it failed: By the time the Java listener is invoked, we're already inside the native event
>   dispatch. Setting doit = false prevents further Java-side handling, but doesn't stop the native
>   Cocoa code that's already in the call stack from continuing its focus management and event
>   re-dispatch.
> 
>   The fundamental problem: Both fixes operate at the Java level, but the recursive ping-pong is
>   initiated by native Cocoa code during its "default handling" (objc_msgSendSuper). We can't
>   intercept or cancel that from Java once it's started.

My conclusion: could pour hours into this and fail to resolve it. It's not causing me enough trouble to proceed.

@buchen thinking laterally about a solution ... the only really bad thing about a bug like this is you can lose a load of unsaved changes. The worst of it could be mitigated by going beyond the classic manual save paradigm, i.e. any features like:
- ~~Periodic autosave~~
- Log and rescue unsaved changes in case of an unplanned exit
- Save all changes transactionally

Any of those would be a good general improvement. But not trivial, of course. Perhaps something for the "one day..." (eines Tages) backlog.

_Update: sorry, I see that autosave is actually available, just off by default_
