### ISSUE TITLE
Flatpak distributed PP v0.67.3 non-functional on Manjaro (Kernel 6.6.10-1)

### ISSUE THREAD

**Issue by driebe** [portfolio-performance/portfolio#3777]
**Describe the bug**
Application crashes 5-15 seconds after start (without having done anything). I find this especially confusing, as my understanding of flatpak / snap / etc. is that those packages are supposed to package the application with their necessary dependencies. So I am unsure of why this is broken for me.

Terminal returns this:
`WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
Feb. 04, 2024 6:26:47 PM org.apache.aries.spifly.BaseActivator log
INFORMATION: Registered provider com.twelvemonkeys.imageio.plugins.bmp.BMPImageReaderSpi of service javax.imageio.spi.ImageReaderSpi in bundle com.twelvemonkeys.imageio.bmp
Feb. 04, 2024 6:26:47 PM org.apache.aries.spifly.BaseActivator log
INFORMATION: Registered provider com.twelvemonkeys.imageio.plugins.bmp.CURImageReaderSpi of service javax.imageio.spi.ImageReaderSpi in bundle com.twelvemonkeys.imageio.bmp
Feb. 04, 2024 6:26:47 PM org.apache.aries.spifly.BaseActivator log
INFORMATION: Registered provider com.twelvemonkeys.imageio.plugins.bmp.ICOImageReaderSpi of service javax.imageio.spi.ImageReaderSpi in bundle com.twelvemonkeys.imageio.bmp
Feb. 04, 2024 6:26:47 PM org.apache.aries.spifly.BaseActivator log
INFORMATION: Registered provider com.twelvemonkeys.imageio.plugins.bmp.BMPImageWriterSpi of service javax.imageio.spi.ImageWriterSpi in bundle com.twelvemonkeys.imageio.bmp
Feb. 04, 2024 6:26:47 PM org.apache.aries.spifly.BaseActivator log
INFORMATION: Registered provider com.twelvemonkeys.imageio.plugins.bmp.ICOImageWriterSpi of service javax.imageio.spi.ImageWriterSpi in bundle com.twelvemonkeys.imageio.bmp

** (Portfolio Performance:28): CRITICAL **: 18:26:48.871: JNI class pointer is NULL for class org/eclipse/swt/accessibility/AccessibleObject

** (Portfolio Performance:28): CRITICAL **: 18:26:48.871: JNI class pointer is NULL for class org/eclipse/swt/accessibility/AccessibleObject

SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
`

**To Reproduce**
Start the application (flatpak version). 

**Expected behavior**
Application not closing out on me ;)

**Screenshots**
-/-

**Desktop (please complete the following information):**
PP: 0.67.3 (Flatpak distributed version)

System:
  Kernel: 6.6.10-1-MANJARO arch: x86_64 bits: 64 compiler: gcc v: 13.2.1
    clocksource: tsc available: hpet,acpi_pm
    parameters: BOOT_IMAGE=/@/boot/vmlinuz-6.6-x86_64
    root=UUID=07717c56-e704-4a27-b6a8-1b3eef974ad2 rw rootflags=subvol=@ quiet
    cryptdevice=UUID=593afc0b-6958-4060-b0cb-0070055aaea7:luks-593afc0b-6958-4060-b0cb-0070055aaea7
    root=/dev/mapper/luks-593afc0b-6958-4060-b0cb-0070055aaea7
    udev.log_priority=3 amdgpu.freesync_video=1
    amdgpu.ppfeaturemask=0xffffffff pcie_port_pm=off
    pcie_aspm.policy=performance
  Desktop: KDE Plasma v: 5.27.10 tk: Qt v: 5.15.12 wm: kwin_wayland vt: 1
    dm: SDDM Distro: Manjaro Linux base: Arch Linux

**Comment by buchen** [comment]
Hi @driebe,

first: is there anything else? The log does look normal. The AccessibleObject errors are always present - for the other messages I simply have no control to suppress them.

second: there is this issue reported on the PP flathub project - does it read like your problem?
https://github.com/flathub/info.portfolio_performance.PortfolioPerformance/issues/28

**Comment by driebe** [comment]
Hi @buchen, it does seem to be the same or a similar issue. In contrast to the user in that other story, I do not get any critical gtk or java runtime error and I don't need to click anywhere for the termination to occur. The log posted above is the only thing the terminal will tell me when running the flatpak app. Is there any way to provide more / better logs for you to better debug the issue?

**Comment by stefanlippuner** [comment]
Hi all

I have a crash that looks very similar to this issue and https://github.com/flathub/info.portfolio_performance.PortfolioPerformance/issues/28. When I open the attached database and click on a different tab (e.g. 'Statement of Assets'), the application crashes after a few seconds. When I run it on the console, I get:

``` 
flatpak run info.portfolio_performance.PortfolioPerformance
# [...]
(Portfolio Performance:22): Gtk-CRITICAL **: 09:30:27.896: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb4484b9405, pid=22, tid=23
#
# JRE version: OpenJDK Runtime Environment 21.9 (17.0.9+7) (build 17.0.9+7)
# Java VM: OpenJDK 64-Bit Server VM 21.9 (17.0.9+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libgtk-3.so.0+0x380405]  gtk_widget_is_sensitive+0x25
#
# Core dump will be written. Default location: Core dumps may be processed with "/lib/systemd/systemd-coredump %P %u %g %s %t 9223372036854775808 %h" (or dumping to /home/stefan/core.22)
#
# An error report file with more information is saved as:
# /home/stefan/hs_err_pid22.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

System config:
 - I'm running flatpak version 1eca0320 (0.67.3)
 - OS: Linux Mint 21.3
 - DE: Cinnamon X11
 - Ryzen 7700X, 32GB RAM, Nvidia 3080


I did some troubleshooting and I found the following:
 - Clearing the user config `~/.var/app/info.portfolio_performance.PortfolioPerformance` does not resolve the issue.
 - Older flatpak versions show the same issue. I tried: (1eca0320,2f21248d,e0aaac07,22f71176,0069584f) and they all showed the same issue.
 - When running the flatpak as root, the issue also does not occur for me.
 - When I run the flatpak application using the Ubuntu/Mint-packaged `openjdk-21-jre`, the issue also does not occur.
 
Logs, test database (brand new): [portfolio_crash.zip](https://github.com/portfolio-performance/portfolio/files/14472292/portfolio_crash.zip)

**Comment by PabDJ** [comment]
> Hi all
> 
> I have a crash that looks very similar to this issue and [flathub/info.portfolio_performance.PortfolioPerformance#28](https://github.com/flathub/info.portfolio_performance.PortfolioPerformance/issues/28). When I open the attached database and click on a different tab (e.g. 'Statement of Assets'), the application crashes after a few seconds. When I run it on the console, I get:
> 
> ```
> flatpak run info.portfolio_performance.PortfolioPerformance
> # [...]
> (Portfolio Performance:22): Gtk-CRITICAL **: 09:30:27.896: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
> #
> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  SIGSEGV (0xb) at pc=0x00007fb4484b9405, pid=22, tid=23
> #
> # JRE version: OpenJDK Runtime Environment 21.9 (17.0.9+7) (build 17.0.9+7)
> # Java VM: OpenJDK 64-Bit Server VM 21.9 (17.0.9+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
> # Problematic frame:
> # C  [libgtk-3.so.0+0x380405]  gtk_widget_is_sensitive+0x25
> #
> # Core dump will be written. Default location: Core dumps may be processed with "/lib/systemd/systemd-coredump %P %u %g %s %t 9223372036854775808 %h" (or dumping to /home/stefan/core.22)
> #
> # An error report file with more information is saved as:
> # /home/stefan/hs_err_pid22.log
> #
> # If you would like to submit a bug report, please visit:
> #   https://bugreport.java.com/bugreport/crash.jsp
> # The crash happened outside the Java Virtual Machine in native code.
> # See problematic frame for where to report the bug.
> #
> ```
> 
> System config:
> 
>     * I'm running flatpak version 1eca0320 (0.67.3)
> 
>     * OS: Linux Mint 21.3
> 
>     * DE: Cinnamon X11
> 
>     * Ryzen 7700X, 32GB RAM, Nvidia 3080
> 
> 
> I did some troubleshooting and I found the following:
> 
>     * Clearing the user config `~/.var/app/info.portfolio_performance.PortfolioPerformance` does not resolve the issue.
> 
>     * Older flatpak versions show the same issue. I tried: (1eca0320,2f21248d,e0aaac07,22f71176,0069584f) and they all showed the same issue.
> 
>     * When running the flatpak as root, the issue also does not occur for me.
> 
>     * When I run the flatpak application using the Ubuntu/Mint-packaged `openjdk-21-jre`, the issue also does not occur.
> 
> 
> Logs, test database (brand new): [portfolio_crash.zip](https://github.com/portfolio-performance/portfolio/files/14472292/portfolio_crash.zip)

I am getting the same error but with version 0.68.3 and even using the following command to run PortfolioPerformance ends with a crash:
```
flatpak run --runtime=org.gnome.Platform/x86_64/44 --env=JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 info.portfolio_performance.PortfolioPerformance

**Comment by PabDJ** [comment]
Any insights about this? @buchen

**Comment by stefanlippuner** [comment]
I've recently updated to Mint 22 and with that my original workaround also resulted in the same crash:

```
# JRE version: OpenJDK Runtime Environment (21.0.3+9) (build 21.0.3+9-Ubuntu-1ubuntu1)
# Java VM: OpenJDK 64-Bit Server VM (21.0.3+9-Ubuntu-1ubuntu1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libgtk-3.so.0+0x35aee5]  gtk_widget_is_sensitive+0x25
```

I guess this could be related to the installed version of GTK 4 (4.6 on Mint 21, 4.14 on Mint 22)? 

I was able to find this thread on the Arch forum: https://bbs.archlinux.org/viewtopic.php?id=285732

With the suggested workaround (running `NO_AT_BRIDGE=1 ./PortfolioPerformance`), the crash no longer occurs. This probably disables all accessibility features, so it's not a great solution... but maybe it can still be useful until the underlying issue is fixed.

**Comment by leplastic** [comment]
This indeed has something to do with upgrade to Linux Mint 22. I did the upgrade within the last two weeks and Portfolio Performance started failing. The way I can reproduce the error is opening any portfolio file (my file or a new one) and start selecting different options on the left sidebar.

```!ENTRY name.abuchen.portfolio.model.ClientFactory 1 0 2025-03-31 18:09:11.580
!MESSAGE Saving portfolio.xml with [XML]
!SESSION 2025-03-31 18:09:58.227 -----------------------------------------------
eclipse.buildId=0.74.2.
java.version=21.0.6
java.vendor=Ubuntu
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=pt_PT
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.equinox.app 4 2 2025-03-31 18:09:59.541
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.equinox.app".
!STACK 0
java.lang.NoClassDefFoundError: org/eclipse/swt/accessibility/AccessibleObject
	at org.eclipse.equinox.launcher.JNIBridge._takedown_splash(Native Method)
	at org.eclipse.equinox.launcher.JNIBridge.takeDownSplash(JNIBridge.java:137)
	at org.eclipse.equinox.launcher.Main.takeDownSplash(Main.java:2194)
	at org.eclipse.equinox.launcher.Main$SplashHandler.run(Main.java:153)
	at org.eclipse.core.runtime.internal.adaptor.DefaultStartupMonitor.applicationRunning(DefaultStartupMonitor.java:72)
	at org.eclipse.equinox.internal.app.EclipseAppHandle$1.run(EclipseAppHandle.java:290)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.applicationRunning(EclipseAppHandle.java:278)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1088)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:165)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.accessibility.AccessibleObject
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 24 more

!ENTRY name.abuchen.portfolio.model.ClientFactory 1 0 2025-03-31 18:09:59.654
!MESSAGE Loaded portfolio.xml with [XML]
```

With the suggestion from @stefanlippuner (using ``NO_AT_BRIDGE=1`` system variable) it works fine without crashing. I guess this is not a Performance Portfolio issue,  but some tips to configure LM to support the application are highly appreciated.
