### ISSUE TITLE
Cannot store existing portfolio as binary

### ISSUE THREAD

**Issue by panic175** [portfolio-performance/portfolio#3895]
**Describe the bug**
I cannot store my existing XML-based portfolio file as binary it creates an invalid file, which cannot be opened.

**To Reproduce**
1. Open existing XML portfolio file
2. Click on 'Save as' and 'Binary'
3. See error, file is created but invalid

Extra: After this error occurs, when trying to save the file the application stores the file under the new name (with extension .portfolio), but the content of the file is in XML format.

```
Tue Apr 02 09:42:48 CEST 2024
Cannot invoke "name.abuchen.portfolio.model.SecurityProperty.getType()" because "p" is null

java.lang.NullPointerException: Cannot invoke "name.abuchen.portfolio.model.SecurityProperty.getType()" because "p" is null
	at name.abuchen.portfolio.model.ProtobufWriter.lambda$9(ProtobufWriter.java:884)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at name.abuchen.portfolio.model.ProtobufWriter.saveSecurities(ProtobufWriter.java:883)
	at name.abuchen.portfolio.model.ProtobufWriter.save(ProtobufWriter.java:775)
	at name.abuchen.portfolio.model.ClientFactory$PlainWriterZIP.save(ClientFactory.java:216)
	at name.abuchen.portfolio.model.ClientFactory.writeFile(ClientFactory.java:641)
	at name.abuchen.portfolio.model.ClientFactory.saveAs(ClientFactory.java:593)
	at name.abuchen.portfolio.ui.editor.ClientInput.lambda$4(ClientInput.java:261)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at name.abuchen.portfolio.ui.editor.ClientInput.doSaveAs(ClientInput.java:258)
	at name.abuchen.portfolio.ui.editor.PortfolioPart.doSaveAs(PortfolioPart.java:423)
	at name.abuchen.portfolio.ui.handlers.SaveAsFileHandler.execute(SaveAsFileHandler.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:298)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:232)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:174)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:165)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4645)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4412)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3988)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:168)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
```

**Example file**

[test.xml.tar.gz](https://github.com/portfolio-performance/portfolio/files/14833656/test.xml.tar.gz)

**Desktop (please complete the following information):**
 - OS: macOS 14.0
 - Version: 0.68.3 (März 2024)
 - Platform: macosx, aarch64
 - Java: 17.0.5+8-LTS, Azul Systems, Inc.

**Comment by buchen** [comment]
The next version will fix such a file upon loading.
