### ISSUE TITLE
Error after opening about box

### ISSUE THREAD

**Issue by greenozon** [portfolio-performance/portfolio#3993]
![image](https://github.com/portfolio-performance/portfolio/assets/765343/38a529cf-b912-4f08-bbc3-8964e774b5d2)

Portfolio Performance

Version: 0.68.4 (квітня 2024)
Platform: win32, x86_64
Java: 17.0.5+8-LTS, Azul Systems, Inc.

© 2012 - 2024, Andreas Buchen. All rights reserved. 

In memory of my mother.

**Comment by greenozon** [comment]
From 1714856872485.log:

```
!SESSION 2024-05-05 00:07:52.293 -----------------------------------------------
eclipse.buildId=0.68.4.
java.version=17.0.5
java.vendor=Azul Systems, Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.apache.aries.spifly.dynamic.bundle 4 0 2024-05-05 00:07:52.818
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.apache.aries.spifly.dynamic.bundle [2]
  Unresolved requirement: Import-Package: org.objectweb.asm; version="[9.6.0,10.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1788)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:269)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:193)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:464)
	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:139)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:338)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:251)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)

```
Steps:
I've unpacked PortfolioPerformance-distro-0.68.4-win32.win32.x86_64.zip  and ran  PortfolioPerformance.exe
