### ISSUE TITLE
Fehler beim Kaufen eines Assets ohne Portfolio oder Account

### ISSUE THREAD

**Issue by simpsus** [portfolio-performance/portfolio#66]
Wenn man dies versucht passiert in der GUI garnichts und auf der console kommt folgende Exception. Ich denke hier könnte man vor dem zeigen des Kaufdialoges prüfen, ob die Voraussetzungen für einen Kauf erfüllt sind.

```
java.lang.NullPointerException
    at name.abuchen.portfolio.ui.dialogs.BuySellSecurityDialog$Model.applyChanges(BuySellSecurityDialog.java:174)
    at name.abuchen.portfolio.ui.dialogs.AbstractDialog.okPressed(AbstractDialog.java:94)
    at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:472)
```

**Comment by cmaoling** [comment]
Unable to reproduce. Seems to be fixed in the meanwhile. => CLOSE?
